title:            A Coding Brain
description:      On Tech, Life, Science, and Arts.
disqus_shortname: acodingbrain
#Comment out url when working locally to resolve base urls correctly
url:              http://blog.acodingbrain.com

# Owner/author information
owner:
  name:           Bassem Makarem
  avatar:         avatar.jpg
  bio:            Poet by soul, doctor by heart, geek by choice, lawyer by mind, and an engineer by extension ;-)
  email:          bassem@acodingbrain.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        makbrain
  facebook:       
  github:         
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   https://plus.google.com/118078418631067582406

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-48210231-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: RSS
    url: /feed.xml
  #- title: Theme Setup
  #  url: /theme-setup
  #- title: External Link
  #  url: http://mademistakes.com
  #  external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Beirut
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
